/* soapCardProcProxy.h
   Generated by gSOAP 2.7.17 from CardClientProc.h
   Copyright(C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapCardProcProxy_H
#define soapCardProcProxy_H
#include "soapH.h"
class CardProc
{   public:
	/// Runtime engine context allocated in constructor
	struct soap *soap;
	/// Endpoint URL of service 'CardProc' (change as needed)
	const char *endpoint;
	/// Constructor allocates soap engine context, sets default endpoint URL, and sets namespace mapping table
	CardProc()
	{ soap = soap_new(); endpoint = "http://localhost"; if (soap && !soap->namespaces) { static const struct Namespace namespaces[] = 
{
	{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
	{"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"ns", "urn:CardProc", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap->namespaces = namespaces; } };
	/// Destructor frees deserialized data and soap engine context
	virtual ~CardProc() { if (soap) { soap_destroy(soap); soap_end(soap); soap_free(soap); } };
	/// Invoke 'CardRegisger' of service 'CardProc' and return error code (or SOAP_OK)
	virtual int ns__CardRegisger(std::string *pRegXML, std::string &strRetXML) { return soap ? soap_call_ns__CardRegisger(soap, endpoint, NULL, pRegXML, strRetXML) : SOAP_EOM; };
	/// Invoke 'CardCheck' of service 'CardProc' and return error code (or SOAP_OK)
	virtual int ns__CardCheck(std::string *pRegXML, std::string &strRetXML) { return soap ? soap_call_ns__CardCheck(soap, endpoint, NULL, pRegXML, strRetXML) : SOAP_EOM; };
	/// Invoke 'CardCheckForNH' of service 'CardProc' and return error code (or SOAP_OK)
	virtual int ns__CardCheckForNH(std::string *pRegXML, std::string &strRetXML) { return soap ? soap_call_ns__CardCheckForNH(soap, endpoint, NULL, pRegXML, strRetXML) : SOAP_EOM; };
};
#endif
