/* sendmsg.h
   Generated by wsdl2h 2.8.15 from http://114.247.234.146:8088/chss/ws/cardSendMessage?wsdl and typemap.dat
   2013-08-06 16:43:08 GMT

   DO NOT INCLUDE THIS FILE DIRECTLY INTO YOUR PROJECT BUILDS
   USE THE soapcpp2-GENERATED SOURCE CODE FILES FOR YOUR PROJECT BUILDS

   gSOAP XML Web services tools.
   Copyright (C) 2000-2013 Robert van Engelen, Genivia Inc. All Rights Reserved.
   Part of this software is released under one of the following licenses:
   GPL or Genivia's license for commercial use.
*/

/** @page page_notes Usage Notes

NOTE:

 - Run soapcpp2 on sendmsg.h to generate the SOAP/XML processing logic.
   Use soapcpp2 -I to specify paths for #import
   To build with STL, 'stlvector.h' is imported from 'import' dir in package.
   Use soapcpp2 -j to generate improved proxy and server classes.
 - Use wsdl2h -c and -s to generate pure C code or C++ code without STL.
 - Use 'typemap.dat' to control namespace bindings and type mappings.
   It is strongly recommended to customize the names of the namespace prefixes
   generated by wsdl2h. To do so, modify the prefix bindings in the Namespaces
   section below and add the modified lines to 'typemap.dat' to rerun wsdl2h.
 - Use Doxygen (www.doxygen.org) on this file to generate documentation.
 - Use wsdl2h -R to generate REST operations.
 - Use wsdl2h -nname to use name as the base namespace prefix instead of 'ns'.
 - Use wsdl2h -Nname for service prefix and produce multiple service bindings
 - Use wsdl2h -d to enable DOM support for xsd:anyType.
 - Use wsdl2h -g to auto-generate readers and writers for root elements.
 - Use wsdl2h -b to auto-generate bi-directional operations (duplex ops).
 - Struct/class members serialized as XML attributes are annotated with a '@'.
 - Struct/class members that have a special role are annotated with a '$'.

WARNING:

   DO NOT INCLUDE THIS ANNOTATED FILE DIRECTLY IN YOUR PROJECT SOURCE CODE.
   USE THE FILES GENERATED BY soapcpp2 FOR YOUR PROJECT'S SOURCE CODE:
   THE soapStub.h FILE CONTAINS THIS CONTENT WITHOUT ANNOTATIONS.

LICENSE:

@verbatim
--------------------------------------------------------------------------------
gSOAP XML Web services tools
Copyright (C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.

This software is released under one of the following two licenses:
GPL or Genivia's license for commercial use.
--------------------------------------------------------------------------------
GPL license.

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 2 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program; if not, write to the Free Software Foundation, Inc., 59 Temple
Place, Suite 330, Boston, MA 02111-1307 USA

Author contact information:
engelen@genivia.com / engelen@acm.org

This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial-use license is available from Genivia, Inc., contact@genivia.com
--------------------------------------------------------------------------------
@endverbatim

*/


//gsoapopt w

/******************************************************************************\
 *                                                                            *
 * Definitions                                                                *
 *   http://ws.ro.chss.greatsoft.net/                                         *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Import                                                                     *
 *                                                                            *
\******************************************************************************/


// STL vector containers (use option -s to remove STL dependency)
#import "stlvector.h"

/******************************************************************************\
 *                                                                            *
 * Schema Namespaces                                                          *
 *                                                                            *
\******************************************************************************/


/* NOTE:

It is strongly recommended to customize the names of the namespace prefixes
generated by wsdl2h. To do so, modify the prefix bindings below and add the
modified lines to typemap.dat to rerun wsdl2h:

ns1 = "http://ws.ro.chss.greatsoft.net/"

*/

#define SOAP_NAMESPACE_OF_ns1	"http://ws.ro.chss.greatsoft.net/"
//gsoap ns1   schema namespace:	http://ws.ro.chss.greatsoft.net/
//gsoap ns1   schema form:	unqualified

/******************************************************************************\
 *                                                                            *
 * Built-in Schema Types and Top-Level Elements and Attributes                *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Forward Declarations                                                       *
 *                                                                            *
\******************************************************************************/



//  Forward declaration of class ns1__sendMessage.
class ns1__sendMessage;

//  Forward declaration of class ns1__sendMessageResponse.
class ns1__sendMessageResponse;

/******************************************************************************\
 *                                                                            *
 * Schema Types and Top-Level Elements and Attributes                         *
 *   http://ws.ro.chss.greatsoft.net/                                         *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Complex Types and Top-Level Elements                                *
 *   http://ws.ro.chss.greatsoft.net/                                         *
 *                                                                            *
\******************************************************************************/


/// "http://ws.ro.chss.greatsoft.net/":sendMessage is a complexType.
/// class ns1__sendMessage operations:
/// - soap_new_ns1__sendMessage(soap*) allocate
/// - soap_new_ns1__sendMessage(soap*, int num) allocate array
/// - soap_new_req_ns1__sendMessage(soap*, ...) allocate, set required members
/// - soap_new_set_ns1__sendMessage(soap*, ...) allocate, set all public members
/// - int soap_read_ns1__sendMessage(soap*, ns1__sendMessage*) deserialize from a stream
/// - int soap_write_ns1__sendMessage(soap, ns1__sendMessage*) serialize to a stream
class ns1__sendMessage
{ public:
/// Element arg0 of type xs:string.
    std::string*                         arg0                           0;	///< Optional element.
/// Element arg1 of type xs:string.
    std::string*                         arg1                           0;	///< Optional element.
/// Element arg2 of type xs:string.
    std::string*                         arg2                           0;	///< Optional element.
/// Element arg3 of type xs:string.
    std::string*                         arg3                           0;	///< Optional element.
/// Element arg4 of type xs:string.
    std::string*                         arg4                           0;	///< Optional element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://ws.ro.chss.greatsoft.net/":sendMessageResponse is a complexType.
/// class ns1__sendMessageResponse operations:
/// - soap_new_ns1__sendMessageResponse(soap*) allocate
/// - soap_new_ns1__sendMessageResponse(soap*, int num) allocate array
/// - soap_new_req_ns1__sendMessageResponse(soap*, ...) allocate, set required members
/// - soap_new_set_ns1__sendMessageResponse(soap*, ...) allocate, set all public members
/// - int soap_read_ns1__sendMessageResponse(soap*, ns1__sendMessageResponse*) deserialize from a stream
/// - int soap_write_ns1__sendMessageResponse(soap, ns1__sendMessageResponse*) serialize to a stream
class ns1__sendMessageResponse
{ public:
/// Element return of type xs:string.
    std::string*                         return_                        0;	///< Optional element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Elements                                              *
 *   http://ws.ro.chss.greatsoft.net/                                         *
 *                                                                            *
\******************************************************************************/


/// Top-level root element "http://ws.ro.chss.greatsoft.net/":sendMessage of type "http://ws.ro.chss.greatsoft.net/":sendMessage.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// Top-level root element "http://ws.ro.chss.greatsoft.net/":sendMessageResponse of type "http://ws.ro.chss.greatsoft.net/":sendMessageResponse.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Attributes                                            *
 *   http://ws.ro.chss.greatsoft.net/                                         *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Services                                                                   *
 *                                                                            *
\******************************************************************************/


//gsoap ns1  service name:	cardSendMessageSoapBinding 
//gsoap ns1  service type:	CardSendMessage 
//gsoap ns1  service port:	http://114.247.234.146:8088/chss/ws/cardSendMessage 
//gsoap ns1  service namespace:	http://ws.ro.chss.greatsoft.net/ 
//gsoap ns1  service transport:	http://schemas.xmlsoap.org/soap/http 

/** @mainpage cardSendMessage Definitions

@section cardSendMessage_bindings Service Bindings

  - @ref cardSendMessageSoapBinding

@section cardSendMessage_more More Information

  - @ref page_notes "Usage Notes"

  - @ref page_XMLDataBinding "XML Data Binding"

  - @ref SOAP_ENV__Header "SOAP Header Content" (when applicable)

  - @ref SOAP_ENV__Detail "SOAP Fault Detail Content" (when applicable)


*/

/**

@page cardSendMessageSoapBinding Binding "cardSendMessageSoapBinding"

@section cardSendMessageSoapBinding_operations Operations of Binding  "cardSendMessageSoapBinding"

  - @ref __ns1__sendMessage

@section cardSendMessageSoapBinding_ports Endpoints of Binding  "cardSendMessageSoapBinding"

  - http://114.247.234.146:8088/chss/ws/cardSendMessage

Note: use wsdl2h option -Nname to change the service binding prefix name


*/

/******************************************************************************\
 *                                                                            *
 * Service Binding                                                            *
 *   cardSendMessageSoapBinding                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__sendMessage                                                       *
 *                                                                            *
\******************************************************************************/


/// Operation "__ns1__sendMessage" of service binding "cardSendMessageSoapBinding"

/**

Operation details:

  - SOAP document/literal style messaging

  - Addressing input action: ""

  - Addressing output action: "Response"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__sendMessage(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    ns1__sendMessage*                   ns1__sendMessage_,
    // output parameters:
    ns1__sendMessageResponse*           ns1__sendMessageResponse_
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__sendMessage(
    struct soap *soap,
    // input parameters:
    ns1__sendMessage*                   ns1__sendMessage_,
    // output parameters:
    ns1__sendMessageResponse*           ns1__sendMessageResponse_
  );
@endcode

C++ proxy class (defined in soapcardSendMessageSoapBindingProxy.h):
@code
  class cardSendMessageSoapBindingProxy;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate greatly improved and easy-to-use proxy classes;

C++ service class (defined in soapcardSendMessageSoapBindingService.h):
@code
  class cardSendMessageSoapBindingService;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate greatly improved and easy-to-use service classes;

*/

//gsoap ns1  service method-protocol:	sendMessage SOAP
//gsoap ns1  service method-style:	sendMessage document
//gsoap ns1  service method-encoding:	sendMessage literal
//gsoap ns1  service method-action:	sendMessage ""
//gsoap ns1  service method-output-action:	sendMessage Response
int __ns1__sendMessage(
    ns1__sendMessage*                   ns1__sendMessage_,	///< Input parameter
    ns1__sendMessageResponse*           ns1__sendMessageResponse_	///< Output parameter
);

/**

@page cardSendMessageSoapBinding Binding "cardSendMessageSoapBinding"

@section cardSendMessageSoapBinding_policy_enablers Policy Enablers of Binding  "cardSendMessageSoapBinding"

Based on policies, this service imports

  - WS-Policy reminders and enablers:
    - WS-Addressing 1.0 (2005/08, accepts 2004/08):
	@code
	#import "wsa5.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsaapi.h"
	soap_register_plugin(soap, soap_wsa); // register the wsa plugin in your code
	// See the user guide gsoap/doc/wsa/html/index.html
	@endcode
    - WS-Addressing (2004/08):
	@code
	#import "wsa.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsaapi.h"
	soap_register_plugin(soap, soap_wsa); // register the wsa plugin in your code
	// See the user guide gsoap/doc/wsa/html/index.html
	@endcode
    - WS-ReliableMessaging 1.0:
	@code
	#import "wsrm5.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsrmapi.h"
	soap_register_plugin(soap, soap_wsa); // register the wsa plugin in your code
	soap_register_plugin(soap, soap_wsrm); // register the wsrm plugin in your code
	// See the user guide gsoap/doc/wsrm/html/index.html
	@endcode
    - WS-ReliableMessaging 1.1:
	@code
	#import "wsrm.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsrmapi.h"
	soap_register_plugin(soap, soap_wsa); // register the wsa plugin in your code
	soap_register_plugin(soap, soap_wsrm); // register the wsrm plugin in your code
	// See the user guide gsoap/doc/wsrm/html/index.html
	@endcode
    - WS-Security (SOAP Message Security) 1.0 (accepts 1.1):
	@code
	#import "wsse.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsseapi.h"
	soap_register_plugin(soap, soap_wsse); // register the wsse plugin in your code
	// See the user guide gsoap/doc/wsse/html/index.html
	@endcode
    - WS-Security (SOAP Message Security) 1.1 (accepts 1.0):
	@code
	#import "wsse11.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsseapi.h"
	soap_register_plugin(soap, soap_wsse); // register the wsse plugin in your code
	// See the user guide gsoap/doc/wsse/html/index.html
	@endcode
    - HTTP Digest Authentication:
	@code
	#include "plugin/httpda.h"
	soap_register_plugin(soap, soap_http_da); // register the HTTP DA plugin in your code
	// See the user guide gsoap/doc/httpda/html/index.html
	@endcode
*/


/******************************************************************************\
 *                                                                            *
 * XML Data Binding                                                           *
 *                                                                            *
\******************************************************************************/


/**

@page page_XMLDataBinding XML Data Binding

SOAP/XML services use data bindings contractually bound by WSDL and auto-
generated by wsdl2h and soapcpp2 (see Service Bindings). Plain data bindings
are adopted from XML schemas as part of the WSDL types section or when running
wsdl2h on a set of schemas to produce non-SOAP-based XML data bindings.

The following readers and writers are C/C++ data type (de)serializers auto-
generated by wsdl2h and soapcpp2. Run soapcpp2 on this file to generate the
(de)serialization code, which is stored in soapC.c[pp]. Include "soapH.h" in
your code to import these data type and function declarations. Only use the
soapcpp2-generated files in your project build. Do not include the wsdl2h-
generated .h file in your code.

Data can be read in XML and deserialized from:
  - a file descriptor, using soap->recvfd = fd
  - a socket, using soap->socket = ...
  - a C++ stream, using soap->is = ...
  - a buffer, using the soap->frecv() callback

Data can be serialized in XML and written to:
  - a file descriptor, using soap->sendfd = fd
  - a socket, using soap->socket = ...
  - a C++ stream, using soap->os = ...
  - a buffer, using the soap->fsend() callback

The following options are available for (de)serialization control:
  - soap->encodingStyle = NULL; to remove SOAP 1.1/1.2 encodingStyle
  - soap_mode(soap, SOAP_XML_TREE); XML without id-ref (no cycles!)
  - soap_mode(soap, SOAP_XML_GRAPH); XML with id-ref (including cycles)
  - soap_set_namespaces(soap, struct Namespace *nsmap); to set xmlns bindings


@section ns1 Top-level root elements of schema "http://ws.ro.chss.greatsoft.net/"

  - <ns1:sendMessage> (use wsdl2h option -g to auto-generate)

  - <ns1:sendMessageResponse> (use wsdl2h option -g to auto-generate)

*/

/* End of sendmsg.h */
