/* soapcardSendMessageSoapBindingProxy.cpp
   Generated by gSOAP 2.8.15 from sendmsg.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under ONE of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#include "soapcardSendMessageSoapBindingProxy.h"

cardSendMessageSoapBindingProxy::cardSendMessageSoapBindingProxy()
{	cardSendMessageSoapBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

cardSendMessageSoapBindingProxy::cardSendMessageSoapBindingProxy(const struct soap &_soap) : soap(_soap)
{ }

cardSendMessageSoapBindingProxy::cardSendMessageSoapBindingProxy(const char *url)
{	cardSendMessageSoapBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
	soap_endpoint = url;
}

cardSendMessageSoapBindingProxy::cardSendMessageSoapBindingProxy(soap_mode iomode)
{	cardSendMessageSoapBindingProxy_init(iomode, iomode);
}

cardSendMessageSoapBindingProxy::cardSendMessageSoapBindingProxy(const char *url, soap_mode iomode)
{	cardSendMessageSoapBindingProxy_init(iomode, iomode);
	soap_endpoint = url;
}

cardSendMessageSoapBindingProxy::cardSendMessageSoapBindingProxy(soap_mode imode, soap_mode omode)
{	cardSendMessageSoapBindingProxy_init(imode, omode);
}

cardSendMessageSoapBindingProxy::~cardSendMessageSoapBindingProxy()
{ }

void cardSendMessageSoapBindingProxy::cardSendMessageSoapBindingProxy_init(soap_mode imode, soap_mode omode)
{	soap_imode(this, imode);
	soap_omode(this, omode);
	soap_endpoint = NULL;
	static const struct Namespace namespaces[] =
{
	{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
	{"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"ns1", "http://ws.ro.chss.greatsoft.net/", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap_set_namespaces(this, namespaces);
}

void cardSendMessageSoapBindingProxy::destroy()
{	soap_destroy(this);
	soap_end(this);
}

void cardSendMessageSoapBindingProxy::reset()
{	destroy();
	soap_done(this);
	soap_init(this);
	cardSendMessageSoapBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

void cardSendMessageSoapBindingProxy::soap_noheader()
{	this->header = NULL;
}

const SOAP_ENV__Header *cardSendMessageSoapBindingProxy::soap_header()
{	return this->header;
}

const SOAP_ENV__Fault *cardSendMessageSoapBindingProxy::soap_fault()
{	return this->fault;
}

const char *cardSendMessageSoapBindingProxy::soap_fault_string()
{	return *soap_faultstring(this);
}

const char *cardSendMessageSoapBindingProxy::soap_fault_detail()
{	return *soap_faultdetail(this);
}

int cardSendMessageSoapBindingProxy::soap_close_socket()
{	return soap_closesock(this);
}

int cardSendMessageSoapBindingProxy::soap_force_close_socket()
{	return soap_force_closesock(this);
}

void cardSendMessageSoapBindingProxy::soap_print_fault(FILE *fd)
{	::soap_print_fault(this, fd);
}

#ifndef WITH_LEAN
#ifndef WITH_COMPAT
void cardSendMessageSoapBindingProxy::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this, os);
}
#endif

char *cardSendMessageSoapBindingProxy::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this, buf, len);
}
#endif

int cardSendMessageSoapBindingProxy::sendMessage(const char *endpoint, const char *soap_action, ns1__sendMessage *ns1__sendMessage_, ns1__sendMessageResponse *ns1__sendMessageResponse_)
{	struct soap *soap = this;
	struct __ns1__sendMessage soap_tmp___ns1__sendMessage;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://114.247.234.146:8088/chss/ws/cardSendMessage";
	if (soap_action == NULL)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__sendMessage.ns1__sendMessage_ = ns1__sendMessage_;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__sendMessage(soap, &soap_tmp___ns1__sendMessage);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__sendMessage(soap, &soap_tmp___ns1__sendMessage, "-ns1:sendMessage", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__sendMessage(soap, &soap_tmp___ns1__sendMessage, "-ns1:sendMessage", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__sendMessageResponse_)
		return soap_closesock(soap);
	ns1__sendMessageResponse_->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__sendMessageResponse_->soap_get(soap, "ns1:sendMessageResponse", "ns1:sendMessageResponse");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
/* End of client proxy code */
