/* soapStub.h
   Generated by gSOAP 2.7.17 from CardClientProc.h
   Copyright(C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapStub_H
#define soapStub_H
#include "stdsoap2.h"

/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#if 0 /* volatile type: do not declare here, declared elsewhere */

#endif

#ifndef SOAP_TYPE_ns__CardRegisgerResponse
#define SOAP_TYPE_ns__CardRegisgerResponse (9)
/* ns:CardRegisgerResponse */
struct ns__CardRegisgerResponse
{
public:
	char **strRetXML;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns__CardRegisger
#define SOAP_TYPE_ns__CardRegisger (10)
/* ns:CardRegisger */
struct ns__CardRegisger
{
public:
	char *pRegXML;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns__CardCheckResponse
#define SOAP_TYPE_ns__CardCheckResponse (12)
/* ns:CardCheckResponse */
struct ns__CardCheckResponse
{
public:
	char **strRetXML;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns__CardCheck
#define SOAP_TYPE_ns__CardCheck (13)
/* ns:CardCheck */
struct ns__CardCheck
{
public:
	char *pRegXML;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns__CardCheckForNHResponse
#define SOAP_TYPE_ns__CardCheckForNHResponse (15)
/* ns:CardCheckForNHResponse */
struct ns__CardCheckForNHResponse
{
public:
	char **strRetXML;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns__CardCheckForNH
#define SOAP_TYPE_ns__CardCheckForNH (16)
/* ns:CardCheckForNH */
struct ns__CardCheckForNH
{
public:
	char *pRegXML;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (17)
/* SOAP Header: */
struct SOAP_ENV__Header
{
#ifdef WITH_NOEMPTYSTRUCT
private:
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (18)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
public:
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (20)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
public:
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
	char *__any;
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (23)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
public:
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (24)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
public:
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
};
#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
typedef char *_XML;
#endif


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Client-Side Call Stubs                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__CardRegisger(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *pRegXML, char **strRetXML);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__CardCheck(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *pRegXML, char **strRetXML);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__CardCheckForNH(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *pRegXML, char **strRetXML);

#endif

/* End of soapStub.h */
