/* soapNHOneCardServiceSoapBindingProxy.h
   Generated by gSOAP 2.8.15 from cardWSDL.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under ONE of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapNHOneCardServiceSoapBindingProxy_H
#define soapNHOneCardServiceSoapBindingProxy_H
#include "soapH.h"

class SOAP_CMAC NHOneCardServiceSoapBindingProxy : public soap
{ public:
	/// Endpoint URL of service 'NHOneCardServiceSoapBindingProxy' (change as needed)
	const char *soap_endpoint;
	/// Constructor
	NHOneCardServiceSoapBindingProxy();
	/// Construct from another engine state
	NHOneCardServiceSoapBindingProxy(const struct soap&);
	/// Constructor with endpoint URL
	NHOneCardServiceSoapBindingProxy(const char *url);
	/// Constructor with engine input+output mode control
	NHOneCardServiceSoapBindingProxy(soap_mode iomode);
	/// Constructor with URL and input+output mode control
	NHOneCardServiceSoapBindingProxy(const char *url, soap_mode iomode);
	/// Constructor with engine input and output mode control
	NHOneCardServiceSoapBindingProxy(soap_mode imode, soap_mode omode);
	/// Destructor frees deserialized data
	virtual	~NHOneCardServiceSoapBindingProxy();
	/// Initializer used by constructors
	virtual	void NHOneCardServiceSoapBindingProxy_init(soap_mode imode, soap_mode omode);
	/// Delete all deserialized data (with soap_destroy and soap_end)
	virtual	void destroy();
	/// Delete all deserialized data and reset to default
	virtual	void reset();
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Get SOAP Header structure (NULL when absent)
	virtual	const SOAP_ENV__Header *soap_header();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Close connection (normally automatic, except for send_X ops)
	virtual	int soap_close_socket();
	/// Force close connection (can kill a thread blocked on IO)
	virtual	int soap_force_close_socket();
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
#ifndef WITH_COMPAT
	virtual	void soap_stream_fault(std::ostream&);
#endif

	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service operation 'nh_pipe' (returns error code or SOAP_OK)
	virtual	int nh_USCOREpipe(ns1__nh_USCOREpipe *ns1__nh_USCOREpipe_, ns1__nh_USCOREpipeResponse *ns1__nh_USCOREpipeResponse_) { return this->nh_USCOREpipe(NULL, NULL, ns1__nh_USCOREpipe_, ns1__nh_USCOREpipeResponse_); }
	virtual	int nh_USCOREpipe(const char *endpoint, const char *soap_action, ns1__nh_USCOREpipe *ns1__nh_USCOREpipe_, ns1__nh_USCOREpipeResponse *ns1__nh_USCOREpipeResponse_);
};
#endif
