/* soapNHOneCardServiceSoapBindingProxy.cpp
   Generated by gSOAP 2.8.15 from cardWSDL.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under ONE of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#include "soapNHOneCardServiceSoapBindingProxy.h"

NHOneCardServiceSoapBindingProxy::NHOneCardServiceSoapBindingProxy()
{	NHOneCardServiceSoapBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

NHOneCardServiceSoapBindingProxy::NHOneCardServiceSoapBindingProxy(const struct soap &_soap) : soap(_soap)
{ }

NHOneCardServiceSoapBindingProxy::NHOneCardServiceSoapBindingProxy(const char *url)
{	NHOneCardServiceSoapBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
	soap_endpoint = url;
}

NHOneCardServiceSoapBindingProxy::NHOneCardServiceSoapBindingProxy(soap_mode iomode)
{	NHOneCardServiceSoapBindingProxy_init(iomode, iomode);
}

NHOneCardServiceSoapBindingProxy::NHOneCardServiceSoapBindingProxy(const char *url, soap_mode iomode)
{	NHOneCardServiceSoapBindingProxy_init(iomode, iomode);
	soap_endpoint = url;
}

NHOneCardServiceSoapBindingProxy::NHOneCardServiceSoapBindingProxy(soap_mode imode, soap_mode omode)
{	NHOneCardServiceSoapBindingProxy_init(imode, omode);
}

NHOneCardServiceSoapBindingProxy::~NHOneCardServiceSoapBindingProxy()
{ }

void NHOneCardServiceSoapBindingProxy::NHOneCardServiceSoapBindingProxy_init(soap_mode imode, soap_mode omode)
{	soap_imode(this, imode);
	soap_omode(this, omode);
	soap_endpoint = NULL;
	static const struct Namespace namespaces[] =
{
	{"SOAP-ENV", "http://www.w3.org/2003/05/soap-envelope", "http://schemas.xmlsoap.org/soap/envelope/", NULL},
	{"SOAP-ENC", "http://www.w3.org/2003/05/soap-encoding", "http://schemas.xmlsoap.org/soap/encoding/", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"ns1", "http://tempurl.org", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap_set_namespaces(this, namespaces);
}

void NHOneCardServiceSoapBindingProxy::destroy()
{	soap_destroy(this);
	soap_end(this);
}

void NHOneCardServiceSoapBindingProxy::reset()
{	destroy();
	soap_done(this);
	soap_init(this);
	NHOneCardServiceSoapBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

void NHOneCardServiceSoapBindingProxy::soap_noheader()
{	this->header = NULL;
}

const SOAP_ENV__Header *NHOneCardServiceSoapBindingProxy::soap_header()
{	return this->header;
}

const SOAP_ENV__Fault *NHOneCardServiceSoapBindingProxy::soap_fault()
{	return this->fault;
}

const char *NHOneCardServiceSoapBindingProxy::soap_fault_string()
{	return *soap_faultstring(this);
}

const char *NHOneCardServiceSoapBindingProxy::soap_fault_detail()
{	return *soap_faultdetail(this);
}

int NHOneCardServiceSoapBindingProxy::soap_close_socket()
{	return soap_closesock(this);
}

int NHOneCardServiceSoapBindingProxy::soap_force_close_socket()
{	return soap_force_closesock(this);
}

void NHOneCardServiceSoapBindingProxy::soap_print_fault(FILE *fd)
{	::soap_print_fault(this, fd);
}

#ifndef WITH_LEAN
#ifndef WITH_COMPAT
void NHOneCardServiceSoapBindingProxy::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this, os);
}
#endif

char *NHOneCardServiceSoapBindingProxy::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this, buf, len);
}
#endif

int NHOneCardServiceSoapBindingProxy::nh_USCOREpipe(const char *endpoint, const char *soap_action, ns1__nh_USCOREpipe *ns1__nh_USCOREpipe_, ns1__nh_USCOREpipeResponse *ns1__nh_USCOREpipeResponse_)
{	struct soap *soap = this;
	struct __ns1__nh_USCOREpipe soap_tmp___ns1__nh_USCOREpipe;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://222.84.227.235:8080/nh_webservice/nhcardWebService";
	if (soap_action == NULL)
		soap_action = "http://tempurl.org/nh_pipe";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__nh_USCOREpipe.ns1__nh_USCOREpipe_ = ns1__nh_USCOREpipe_;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__nh_USCOREpipe(soap, &soap_tmp___ns1__nh_USCOREpipe);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__nh_USCOREpipe(soap, &soap_tmp___ns1__nh_USCOREpipe, "-ns1:nh_pipe", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__nh_USCOREpipe(soap, &soap_tmp___ns1__nh_USCOREpipe, "-ns1:nh_pipe", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__nh_USCOREpipeResponse_)
		return soap_closesock(soap);
	ns1__nh_USCOREpipeResponse_->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__nh_USCOREpipeResponse_->soap_get(soap, "ns1:nh_pipeResponse", "ns1:nh_pipeResponse");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
/* End of client proxy code */
